Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,6 +23,14 @@ jobs:
           node-version: '20'  # Specify the Node.js version you are using
           cache: 'npm'  # Cache npm dependencies
 
+      # Check for lock file existence
+      - name: Check for package-lock.json
+        run: |
+          if [ ! -f portfolio/package-lock.json ]; then
+            echo "package-lock.json not found in portfolio directory!"
+            exit 1
+          fi
+
       # Install dependencies
       - name: Install dependencies
         run: |
